### ISSUE TITLE
Flag to only report *direct* dependencies

### ISSUE THREAD

**Issue by mstoykov** [dop251/modtools#2]
I think it will be a good idea if `modtools check` (but also probably `modtools update`) work only on *direct* dependencies instead of all of them. 

If there is any interest, and we can agree on the flag I can try to add it?

**Comment by dop251** [comment]
To me it would kind of defeat the purpose, because the point is to ensure all dependencies are up to date so that there are no vulnerabilities due to outdated dependencies, both direct and indirect... Having said that I would not mind a flag as long as the default behaviour remains the same.
